version: '3.8'

services:
  sage-ai:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./chat_data:/app/chat_data
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s 